name: Build and Push to ECR
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['app/**']
permissions:
  id-token: write
  contents: read
  security-events: write
jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: ecs2-api
      AWS_REGION: eu-north-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} ./app --platform linux/amd64

      - name: Scan with Grype
        uses: anchore/scan-action@v4
        with:
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          fail-build: false
          severity-cutoff: critical
          output-format: sarif

      - name: Upload scan results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Push to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}